version: '3'
services:
  controller:
    container_name: controller
    hostname: controller
    image: bobuhiro11/containerized-devstack-controller
    tty: true
    cap_add:
      - ALL
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
      net.ipv6.conf.default.disable_ipv6: 0
    environment:
      - HOST_IP=172.28.0.2
    networks:
      management_network:
        ipv4_address: 172.28.0.2
  compute-1:
    container_name: compute-1
    hostname: compute-1
    image: bobuhiro11/containerized-devstack-compute-1
    tty: true
    cap_add:
      - ALL
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
      net.ipv6.conf.default.disable_ipv6: 0
    environment:
      - HOST_IP=172.28.0.3
    networks:
      management_network:
        ipv4_address: 172.28.0.3
  compute-2:
    container_name: compute-2
    hostname: compute-2
    image: bobuhiro11/containerized-devstack-compute-2
    tty: true
    cap_add:
      - ALL
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
      net.ipv6.conf.default.disable_ipv6: 0
    environment:
      - HOST_IP=172.28.0.4
    networks:
      management_network:
        ipv4_address: 172.28.0.4
networks:
  management_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/24
