version: '3'
services:
  controller:
    container_name: controller
    hostname: controller
    image: bobuhiro11/containerized-devstack-controller
    tty: true
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - DAC_READ_SEARCH
      - FOWNER
      - FSETID
      - IPC_LOCK
      - IPC_OWNER
      - KILL
      - LEASE
      - LINUX_IMMUTABLE
      - MAC_ADMIN
      - MAC_OVERRIDE
      - MKNOD
      - NET_ADMIN
      - NET_BIND_SERVICE
      - NET_BROADCAST
      - NET_RAW
      - SETFCAP
      - SETGID
      - SETPCAP
      - SETUID
      - SYS_ADMIN
      - SYS_CHROOT
      - SYS_NICE
      - SYS_PACCT
      - SYS_PTRACE
      - SYS_RAWIO
      - SYS_RESOURCE
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    devices:
      - '/dev/net/tun:/dev/net/tun'
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
      net.ipv6.conf.default.disable_ipv6: 0
    environment:
      - HOST_IP=172.28.0.2
    networks:
      management_network:
        ipv4_address: 172.28.0.2
  compute-1:
    container_name: compute-1
    hostname: compute-1
    image: bobuhiro11/containerized-devstack-compute-1
    tty: true
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - DAC_READ_SEARCH
      - FOWNER
      - FSETID
      - IPC_LOCK
      - IPC_OWNER
      - KILL
      - LEASE
      - LINUX_IMMUTABLE
      - MAC_ADMIN
      - MAC_OVERRIDE
      - MKNOD
      - NET_ADMIN
      - NET_BIND_SERVICE
      - NET_BROADCAST
      - NET_RAW
      - SETFCAP
      - SETGID
      - SETPCAP
      - SETUID
      - SYS_ADMIN
      - SYS_CHROOT
      - SYS_NICE
      - SYS_PACCT
      - SYS_PTRACE
      - SYS_RAWIO
      - SYS_RESOURCE
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    devices:
      - '/dev/net/tun:/dev/net/tun'
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
      net.ipv6.conf.default.disable_ipv6: 0
    environment:
      - HOST_IP=172.28.0.3
    networks:
      management_network:
        ipv4_address: 172.28.0.3
  compute-2:
    container_name: compute-2
    hostname: compute-2
    image: bobuhiro11/containerized-devstack-compute-2
    tty: true
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - DAC_READ_SEARCH
      - FOWNER
      - FSETID
      - IPC_LOCK
      - IPC_OWNER
      - KILL
      - LEASE
      - LINUX_IMMUTABLE
      - MAC_ADMIN
      - MAC_OVERRIDE
      - MKNOD
      - NET_ADMIN
      - NET_BIND_SERVICE
      - NET_BROADCAST
      - NET_RAW
      - SETFCAP
      - SETGID
      - SETPCAP
      - SETUID
      - SYS_ADMIN
      - SYS_CHROOT
      - SYS_NICE
      - SYS_PACCT
      - SYS_PTRACE
      - SYS_RAWIO
      - SYS_RESOURCE
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    devices:
      - '/dev/net/tun:/dev/net/tun'
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
      net.ipv6.conf.default.disable_ipv6: 0
    environment:
      - HOST_IP=172.28.0.4
    networks:
      management_network:
        ipv4_address: 172.28.0.4
networks:
  management_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/24
