name: action
on:
  push:
    branches: [main]
  schedule:
    - cron:  '0 0 * * *'
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: hadolint for controller
        run: docker run -e "HADOLINT_IGNORE=DL3008" --rm -i hadolint/hadolint < controller/Dockerfile
      - name: hadolint for compute
        run: docker run -e "HADOLINT_IGNORE=DL3008" --rm -i hadolint/hadolint < compute/Dockerfile
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Init docker-compose
        run: |
          docker-compose up -d
          sleep 1800
      - name: Exec OpenStack CLI
        run: |
          docker-compose logs -t --tail=100
          docker-compose exec -T --user stack controller /bin/bash -c \
            'openstack compute service list'
          net_id=$(docker-compose exec -T --user stack controller /bin/bash -c \
            'openstack network show private -f json 2>/dev/null | jq -r .id' | tr -d "\r\n")
          docker-compose exec -T --user stack controller /bin/bash -c \
            "nova boot --image cirros-0.5.2-x86_64-disk --flavor m1.medium --nic net-id=$net_id testvm"
          sleep 10
          docker-compose exec -T --user stack controller /bin/bash -c \
            "nova list"
          docker-compose exec -T --user stack controller /bin/bash -c \
            "nova list" | grep ACTIVE
          docker-compose exec -T controller /bin/bash -c "systemctl disable devstack"
          docker-compose exec -T compute-1  /bin/bash -c "systemctl disable devstack"
          docker-compose exec -T compute-2  /bin/bash -c "systemctl disable devstack"
          docker-compose stop
          docker ps -a
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to Docker Hub for PR
        if: github.ref != 'refs/heads/main' && github.event_name != 'schedule'
        run: |
          docker commit controller bobuhiro11/containerized-devstack-controller:${{ github.sha }}
          docker commit compute-1 bobuhiro11/containerized-devstack-compute-1:${{ github.sha }}
          docker commit compute-2 bobuhiro11/containerized-devstack-compute-2:${{ github.sha }}
          docker push bobuhiro11/containerized-devstack-controller:${{ github.sha }}
          docker push bobuhiro11/containerized-devstack-compute-1:${{ github.sha }}
          docker push bobuhiro11/containerized-devstack-compute-2:${{ github.sha }}
      - name: Push to Docker Hub for latest
        if: github.ref == 'refs/heads/main' && github.event_name != 'schedule'
        run: |
          docker commit controller bobuhiro11/containerized-devstack-controller:latest
          docker commit compute-1 bobuhiro11/containerized-devstack-compute-1:latest
          docker commit compute-2 bobuhiro11/containerized-devstack-compute-2:latest
          docker push bobuhiro11/containerized-devstack-controller:latest
          docker push bobuhiro11/containerized-devstack-compute-1:latest
          docker push bobuhiro11/containerized-devstack-compute-2:latest
